---
# tasks file for nginx
- name: installing {{ pkg }}
  apt: name={{ pkg }} state=present
- name: deploy
  copy: src=index.html dest=/var/www/html/
  notify: restartserver
- name: confirm installation
  command: which {{ pkg }}
