---
- hosts: all
  connection: ssh
  gather_facts: no
  vars_files:
          - vars.yml
  tasks:
          - name: copying the file
            copy:
                    src={{ spath }}
                    dest={{ dpath }}
                    mode=0777

